# Import and Data

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('/Users/lardof/Machine Learning/boston.csv')

In [4]:
from sklearn.model_selection import train_test_split

## Polinom Dönüşüm

In [5]:
X = df.drop('PRICE', axis=1)
y = df['PRICE']

In [6]:
from sklearn.preprocessing import PolynomialFeatures
poly_conv = PolynomialFeatures(degree=2, include_bias=False)
poly_feat = poly_conv.fit_transform(X)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=9)


## Standard Scaler

In [10]:
from sklearn.preprocessing import StandardScaler


In [12]:
scaler = StandardScaler()

In [14]:
X_train.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  339.000000  339.000000  339.000000  339.000000  339.000000  339.000000   
mean     3.974304   11.345133   11.402006    0.070796    0.559236    6.259537   
std      9.595737   23.166564    6.929703    0.256864    0.115815    0.692364   
min      0.006320    0.000000    0.740000    0.000000    0.385000    3.863000   
25%      0.083785    0.000000    5.190000    0.000000    0.453000    5.877000   
50%      0.279570    0.000000    9.900000    0.000000    0.538000    6.208000   
75%      3.735965   12.500000   18.100000    0.000000    0.639000    6.566000   
max     88.976200   95.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  339.000000  339.000000  339.000000  339.000000  339.000000  339.000000   
mean    69.144248    3.758624    9.825959  415.442478   18.433333  357.828643   
std     28.331394    2.170541    8.769354  169.540919    2.171230   87.921649   
min      2.900000    1.129600    1.000000  187.000000   12.600000    2.520000   
25%     44.700000    2.052100    4.000000  284.000000   17.350000  374.635000   
50%     79.200000    2.987900    5.000000  351.000000   19.000000  391.250000   
75%     94.600000    5.116700   24.000000  666.000000   20.200000  396.210000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  339.000000  
mean    12.867729  
std      7.270231  
min      1.730000  
25%      7.300000  
50%     11.450000  
75%     17.025000  
max     37.970000

In [18]:
scaler.fit(X_train)

StandardScaler()

In [20]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


In [21]:
X_train

array([[-0.40334855, -0.49044403,  0.07630551, ...,  1.18387295,
         0.40574776, -0.87991305],
       [-0.3801916 , -0.49044403, -0.75179198, ..., -0.47662417,
         0.24058441, -1.2284219 ],
       [-0.34553759,  0.37414529, -1.07407076, ..., -2.50612065,
         0.29001951, -0.69945984],
       ...,
       [-0.37435957, -0.49044403,  2.05911487, ...,  0.30749947,
         0.0166457 ,  1.98254311],
       [-0.41321958,  2.96791323, -1.35732924, ..., -0.66112385,
         0.37715742, -0.94741081],
       [ 0.54403547, -0.49044403,  0.96799165, ...,  0.81487359,
         0.44504525,  1.47837615]])

## Ridge Regr 

In [22]:
from sklearn.linear_model import Ridge

In [23]:
ridge_model = Ridge(alpha=10)

In [24]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [25]:
ridge_pred = ridge_model.predict(X_test)

In [27]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error


In [28]:
print('R^2     :', round(r2_score(y_test, ridge_pred), 2))
print('MAE     :', round(mean_absolute_error(y_test, ridge_pred), 2))
print('RMSE    :', round(np.sqrt(mean_squared_error(y_test, ridge_pred)), 2))


R^2     : 0.77
MAE     : 2.98
RMSE    : 4.33


In [43]:
ridge_cv.coef_
#Ridge kullanmadığı coefleri çok daha düşük bir seviyeye çekiyor.

array([-0.95484966,  0.85069774,  0.19509074,  0.59777511, -1.6471688 ,
        2.76734683,  0.02858156, -2.58397462,  1.89575466, -1.42066011,
       -1.84403783,  0.73185936, -3.7785473 ])

## Alpha Değeri İçin

In [29]:
from sklearn.linear_model import RidgeCV

In [32]:
ridge_cv = RidgeCV(alphas=(0.001,0.01,0.1,1,10), scoring='neg_mean_absolute_error')

In [33]:
ridge_cv.fit(X_train,y_train)

RidgeCV(alphas=(0.001, 0.01, 0.1, 1, 10), scoring='neg_mean_absolute_error')

In [35]:
ridge_cv.alpha_

10.0

## Lasso

In [37]:
from sklearn.linear_model import LassoCV

In [38]:
lasso_cv = LassoCV(eps=0.1, n_alphas=100, cv=5)

In [39]:
lasso_cv.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [40]:
lasso_cv.alpha_

0.6771577393956378

In [45]:
lasso_cv.coef_
#Lasso direk bası coefleri atıyor.

array([-0.15144721,  0.        , -0.        ,  0.14300536, -0.        ,
        2.84910753,  0.        , -0.        , -0.        , -0.        ,
       -1.35589703,  0.28573598, -3.66763855])

In [47]:
lasso_pred = lasso_cv.predict(X_test)

In [48]:
print('R^2     :', round(r2_score(y_test, lasso_pred), 2))
print('MAE     :', round(mean_absolute_error(y_test, lasso_pred), 2))
print('RMSE    :', round(np.sqrt(mean_squared_error(y_test, lasso_pred)), 2))


R^2     : 0.7
MAE     : 3.46
RMSE    : 4.99


## Elastic Net
Lasslo ile Ridge birleşmiş hali.

In [58]:
from sklearn.linear_model import ElasticNetCV

In [59]:
elastic_mode = ElasticNetCV(l1_ratio=(0.01,0.1,0.3,0.5,0.7,0.9,0.95,0.99,1), tol=0.01)

In [60]:
help(ElasticNetCV)
# 1'e yakınsa Lasso, 0'a yakında Ridge

Help on class ElasticNetCV in module sklearn.linear_model._coordinate_descent:

class ElasticNetCV(sklearn.base.RegressorMixin, LinearModelCV)
 |  ElasticNetCV(*, l1_ratio=0.5, eps=0.001, n_alphas=100, alphas=None, fit_intercept=True, precompute='auto', max_iter=1000, tol=0.0001, cv=None, copy_X=True, verbose=0, n_jobs=None, positive=False, random_state=None, selection='cyclic')
 |  
 |  Elastic Net model with iterative fitting along a regularization path.
 |  
 |  See glossary entry for :term:`cross-validation estimator`.
 |  
 |  Read more in the :ref:`User Guide <elastic_net>`.
 |  
 |  Parameters
 |  ----------
 |  l1_ratio : float or list of float, default=0.5
 |      Float between 0 and 1 passed to ElasticNet (scaling between
 |      l1 and l2 penalties). For ``l1_ratio = 0``
 |      the penalty is an L2 penalty. For ``l1_ratio = 1`` it is an L1 penalty.
 |      For ``0 < l1_ratio < 1``, the penalty is a combination of L1 and L2
 |      This parameter can be a list, in which case

In [63]:
elastic_model.fit(X_train, y_train)

ElasticNetCV()

In [64]:
elastic_model.l1_ratio_

0.5

In [65]:
elastic_model.coef_

array([-0.99765524,  0.93712937,  0.34085021,  0.57707479, -1.84721669,
        2.71331401,  0.05689778, -2.79161774,  2.32433692, -1.7898316 ,
       -1.91286429,  0.7286279 , -3.90775533])

In [69]:
elastic_pred = elastic_model.predict(X_test)

In [70]:
print('R^2     :', round(r2_score(y_test, elastic_pred), 2))
print('MAE     :', round(mean_absolute_error(y_test, elastic_pred), 2))
print('RMSE    :', round(np.sqrt(mean_squared_error(y_test, elastic_pred)), 2))


R^2     : 0.78
MAE     : 2.99
RMSE    : 4.31
